scripts/ddlm_validate: tests/cases/ddlm_validate_048.inp data_faulty_su_link: WARNING, missing data item definition in the DDLm dictionary -- the _faulty_relation_category.linked_su data item is defined as being linked to the _faulty_relation_category.strange_link data item, however, the definition of the linked data item is not provided.
scripts/ddlm_validate: tests/cases/ddlm_validate_048.inp data_faulty_su_link: WARNING, the '_faulty_relation_category.strange_link' data item is required by the '_faulty_relation_category.linked_su' data item, but was not found.
scripts/ddlm_validate: tests/cases/ddlm_validate_048.inp data_faulty_link_with_faulty: WARNING, missing data item definition in the DDLm dictionary -- the _faulty_relation_category_looped.link_item data item is defined as being linked to the _faulty_relation_category_looped.main_item data item, however, the definition of the linked data item is not provided.
scripts/ddlm_validate: tests/cases/ddlm_validate_048.inp data_faulty_link_with_faulty: WARNING, missing category key data item -- the _faulty_relation_category_looped.id data item must be provided in the loop containing the ['_faulty_relation_category_looped.link_item'] data items.
scripts/ddlm_validate: tests/cases/ddlm_validate_048.inp data_faulty_link_with_faulty: WARNING, the '_faulty_relation_category_looped.link_item' data item contains value '4' that was not found among the values of the linked '_faulty_relation_category_looped.main_item' data item.
scripts/ddlm_validate: tests/cases/ddlm_validate_048.inp data_faulty_link_with_faulty: WARNING, data item '_faulty_relation_category_looped.main_item' was not found in the provided dictionaries.
scripts/ddlm_validate: tests/cases/ddlm_validate_048.inp data_faulty_link_no_faulty: WARNING, missing data item definition in the DDLm dictionary -- the _faulty_relation_category_looped.link_item data item is defined as being linked to the _faulty_relation_category_looped.main_item data item, however, the definition of the linked data item is not provided.
scripts/ddlm_validate: tests/cases/ddlm_validate_048.inp data_faulty_link_no_faulty: WARNING, the '_faulty_relation_category_looped.main_item' data item is required by the '_faulty_relation_category_looped.link_item' data item, but was not found.
